In [5]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [4]:
!which python3

'which' is not recognized as an internal or external command,
operable program or batch file.


In [6]:
import numpy as np


In [8]:
l=[i for i in range(10)]

In [9]:
ar = np.array(l) # shit + double tab gives u info

In [10]:
ar


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ar.min()

0

In [ ]:
ar.std() # standard deviation value

In [ ]:
ar.mean() # moyenne

In [ ]:
ar.dtype

In [13]:
ex= list([1,2,3,'s'])

In [14]:
np.array(ex)

array(['1', '2', '3', 's'], dtype='<U11')

In [17]:
m= np.array([[1,2],[3,4]]); m

array([[1, 2],
       [3, 4]])

In [18]:
m[0][1]

2

In [19]:
m[0][1] = 9

In [20]:
m

array([[1, 9],
       [3, 4]])

In [21]:
m.shape # shape matric de m je pense

(2, 2)

In [22]:
m2 = np.array([1,2,3,4,5],ndmin=2); m2 

array([[1, 2, 3, 4, 5]])

In [23]:
m2.shape

(1, 5)

In [24]:
m2

array([[1, 2, 3, 4, 5]])

In [25]:
m2.shape = (5,1)

In [26]:
m2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [28]:
m2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [29]:
b = np.linspace(0,2,4) # start de  0 , stop à 2 , 4  valeur  alors donne une liste avec même écart de 0 à 4

In [30]:
b

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [31]:
b**2 # met tableau d'avant tous en puissance carré

array([0.        , 0.44444444, 1.77777778, 4.        ])

In [32]:
np.arrange(24)

AttributeError: module 'numpy' has no attribute 'arrange'

In [33]:
c = np.arange(24).reshape(2,3,4); c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
c.shape

(2, 3, 4)

In [35]:
c.ndim # dimensions x , y , z

3

In [46]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
# lignes 2 et 3  et colonnes 1 et 2
ar[0:3,0:3] # 0 est comme un pointeur avant la ligne ou colonne et 3 index est same thing

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
# juste la 2éme ligne et un tableau à 1 dimension
ar[1,:]

array([4, 5, 6])

In [52]:
#la derniére colonne
ar[:,-1] # -1 indique la derniére colone

array([3, 6, 9])

In [48]:
s = " personne ecoute ce que je reaconte"
s[0:9]

' personne'

In [58]:
ar==2

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [63]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,4],[3,4]])
A,B

(array([[1, 1],
        [0, 1]]),
 array([[2, 4],
        [3, 4]]))

In [61]:
A+B

array([[3, 5],
       [3, 5]])

In [65]:
a = np.array([1.7,2.8,3])

In [66]:
a.argmax() # position de la valeur max de la liste

2

In [67]:
b= np.array([[1,2],[3,4]])

In [68]:
b

array([[1, 2],
       [3, 4]])

In [69]:
sum(b)

array([4, 6])

In [70]:
b.sum(axis=1) # axis 1 colonne , axis 0 lignes

array([3, 7])

In [71]:
b.sum(axis=0)

array([4, 6])

In [72]:
np.array([1,2,3,4]).cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [73]:
np.arange(10) # 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
x= np.tile(3,8); x

array([3, 3, 3, 3, 3, 3, 3, 3])

In [77]:
z = np.zeros((2,4)); z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
type(z) # n dimensional array

numpy.ndarray

In [79]:
z.dtype

dtype('float64')

In [81]:
6*x

array([18, 18, 18, 18, 18, 18, 18, 18])

In [82]:
np.ones((2,4), dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [84]:
np.diag(np.array([1,4]))

array([[1, 0],
       [0, 4]])